# Copyright (c) 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author:  Philippe Sauter <phsauter@iis.ee.ethz.ch>

name: Backend

on:
  workflow_call:

jobs:
  oseda-caching:
    runs-on: ubuntu-latest
    steps:
      - name: "Cache OSEDA image"
        uses: ./.github/actions/oseda-caching

  backend:
    needs: oseda-caching
    runs-on: ubuntu-latest
    steps:
      - name: Setup OSEDA container
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: "make yosys && make openroad && make klayout"
