# Copyright (c) 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author:  Philippe Sauter <phsauter@iis.ee.ethz.ch>

name: Short Flow

on: [push, pull_request, workflow_dispatch]

jobs:
  oseda-caching:
    runs-on: ubuntu-latest
    steps:
      - name: "Cache OSEDA image"
        uses: ./.github/actions/oseda-caching

  simulation:
    needs: oseda-caching
    runs-on: ubuntu-latest
    steps:
      - name: Run simulation commands in OSEDA
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: "make sw && make verilator"

  synthesis:
    needs: oseda-caching
    runs-on: ubuntu-latest
    steps:
      - name: Setup OSEDA container
        uses: ./.github/actions/oseda-cmd
        with:
          cmd: "make yosys"
